spin_manifest_version = 2

[application]
authors = ["aldwinyu"]
description = ""
name = "crud-list"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "crud-list"

[variables]
telegram_bot_token = { required = true }

[component.crud-list]
source = "target/crud-list.wasm"
exclude_files = ["**/node_modules", "**/add"]
allowed_outbound_hosts = [ "https://api.telegram.org" ]
sqlite_databases = ["default"]
[component.crud-list.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
[component.crud-list.variables]
telegram_bot_token = "{{ telegram_bot_token }}"

[[trigger.http]]
route = "/add"
component = "add"

[component.add]
source = "add/target/add.wasm"
[component.add.build]
command = "npm run build"
workdir = "add"

[[trigger.http]]
route = "/list"
component = "list"

[component.list]
source = "list/target/list.wasm"
[component.list.build]
command = "npm run build"
workdir = "list"

[[trigger.http]]
route = "/update"
component = "update"

[component.update]
source = "update/target/update.wasm"
[component.update.build]
command = "npm run build"
workdir = "update"

