spin_manifest_version = 2

[application]
authors = ["aldwinyu"]
description = ""
name = "crud-list"
version = "0.1.0"

[[trigger.http]]
route = "/v1/messages/..."
component = "messages"

[component.messages]
source = "messages/target/messages.wasm"
sqlite_databases = ["default"]
[component.messages.build]
watch = ["src/**/*.ts", "package.json", "spin.toml"]
command = "npm run build"
workdir = "messages"